### ISSUE TITLE
In Chuwi larkbox X api-dev crashes each time the api file is edited

### ISSUE THREAD

**Issue by jjjorgina** [Protofy-xyz/Protofy#18] opened 2024-01-22 17:17 UTC
## Expected Behavior
api-dev should keep working as usual when changing its content

## Current Behavior
After changing its content, api-dev crashes. Works good for the first "save", but then crashes after second one.
We have also seen that the CPU usage goes to 100% when running the project.

## Steps to Reproduce
1. Go to an api function. (\packages\app\bundles\custom\apis\apifile.ts)
2. Change its content and save.
3. Change again and it will crash

## Context (Environment)
- Default setup
- OS: Windows 11
   Edición	Windows 11 Home
Versión	22H2
Instalado el	‎21/‎10/‎2023
Versión del sistema operativo	22621.3007
Experiencia	Windows Feature Experience Pack 1000.22681.1000.0

- Browser: Chrome
- Environment: dev (start-dev-full)
- Hardware: Chuwi LarkBox X
   Nombre del dispositivo	DESKTOP-FFUDIMA
Procesador	Intel(R) N100   800 MHz
RAM instalada	12,0 GB (11,7 GB usable)
Identificador de dispositivo	CD0EC0D5-A81E-4D6F-A5A1-97D29F1314C4
Id. del producto	00356-02440-92629-AAOEM
Tipo de sistema	Sistema operativo de 64 bits, procesador basado en x64
Lápiz y entrada táctil	La entrada táctil o manuscrita no está disponible para esta pantalla

## Issue demo

https://github.com/Protofy-xyz/Protofy/assets/111370411/8e6999ce-e0b4-4592-9a43-7a1e25aed414

![CPUUsage](https://github.com/Protofy-xyz/Protofy/assets/111370411/cc7b7f60-57fb-4fb6-b47b-77c75def7527)nnn

**Comment by lluis-protofy-xyz** [comment] 2024-01-24 17:45
Hi!

The CPU frequency is a bit suspicious. This computer should be running at around 2GHz.

I've found that these CPUs reduce their clock speed depending on the temperature, causing a drop in performance https://forum.chuwi.com/t/larkbox-fan-noise-and-temperatures/14595/73
 
Are you using the official power supply? Maybe the one you're using is limiting the maximum current available and the CPU can't run at its true frequency.

Thanks

**Comment by theG3n15** [comment] 2024-01-26 14:10
We close the issue as it seems that the problem is with the CPU of that computer (we recommend you having that computer checked). We have tested with less powerful CPU, Intel(R) Celron(R) J4125, and the api-dev works fine.

**Closed by theG3n15** 2024-01-26 14:10 UTC
Labels: bug
